### ISSUE TITLE
make MOM6 and MOM4/5 grid dimensions specified at runtime via grid_spec.nc

### ISSUE THREAD

**Issue by StevePny** [UMD-AOSC/Ocean-LETKF#115]
For the 'DYNAMIC' compilation option, follow template in nemo version (common_nemo.f90) and make the model dimensions read from file and allocate the relevant arrays.

**Comment by cd10kfsu** [comment]
Done with the latest version [c0ac018](https://github.com/UMD-AOSC/Ocean-LETKF/commit/c0ac0187f1ff22719484235b043980483e39b09f)
