### ISSUE TITLE
unallocated vars and missing vars for MOM6 ifdef DYNAMIC

### ISSUE THREAD

**Issue by cd10kfsu** [UMD-AOSC/Ocean-LETKF#130]
This issue is with the label "bugs"

@StevePny @sanAkel 
`set_common_model` sets the common vars and read in static vars from files. 

`Ifdef DYNAMIC`, a lot of variables are dynamic allocated, by the subroutine `initialize_vars_model` in  `mom6/vars_model.f90`
https://github.com/UMD-AOSC/Ocean-LETKF/blob/ecf6a877ff93b324e7217dfd72f961e391c2a2f5/src/model_specific/mom6/vars_model.f90#L99-L116

**However, the variables `depth`, `height`, `wet` are not allocated** from this subroutine, and they are then used directly by the subroutine `set_common_oceanmodel` in `mom6/common_mom6.f90`. For example,
https://github.com/UMD-AOSC/Ocean-LETKF/blob/ecf6a877ff93b324e7217dfd72f961e391c2a2f5/src/model_specific/mom6/common_mom6.f90#L170-L177

Will run the small test to check it.

**Comment by sanAkel** [comment]
I will respond in detail
- later. However, quick remark:

We prefer not to put a number (such as "5") next to GEOS. So please just say and write GEOS. Any version number or such would be a SHA or a released tag for that repo.
Thanks!

**Comment by cd10kfsu** [comment]
@StevePny @sanAkel 
Solved the second problem. 
Found `MOM.res.nc` under `scratch/RESTART`, which has var `h(Time, Layer, lath, lonh)`.
Start to test the first bug

**Comment by sanAkel** [comment]
> @StevePny @sanAkel 
> 
> Solved the second problem. 
> 
> Found `MOM.res.nc` under `scratch/RESTART`, which has var `h(Time, Layer, lath, lonh)`.
> 
> Start to test the first bug
> 
> 

Right! Restart has that. Good eye!

But we ought to use "ocean_static.nc" -- look into "data_table" and uncomment it.

The fields written out in that ocean_static file and "bkg" are what we need to save every hour.

Best we tag up on Monday.

**Comment by cd10kfsu** [comment]
thanks Santha! See you on Monday. I will fly solo for a while

**Comment by cd10kfsu** [comment]
@StevePny @sanAkel 
With a test case, I found the following 3 problems:

#### 1. Unallocated vars 
`ifdef DYNAMIC`, allocation for the following vars are missing:
```
  ALLOCATE(fcori2d(nlon,nlat))
  ALLOCATE(area_t(nlon,nlat))
  ALLOCATE(height(nlon,nlat,nlev))
  ALLOCATE(wet(nlon,nlat))
  ALLOCATE(depth(nlon,nlat))
```
#### 2. incorrect loop index 
https://github.com/UMD-AOSC/Ocean-LETKF/blob/ecf6a877ff93b324e7217dfd72f961e391c2a2f5/src/model_specific/mom6/common_mom6.f90#L156

Here we should use `lat(j-1)` and `lat(j+1)`, (loop over index **j** instead of **i** since `j` is for `lat` while `i` is for `lon`)
```
d2 = cos(lat(i-1)) * cos(lat(i+1)) * (sin(dlon/2.0))**2
```

#### 3. incorrect assignment (needs help)
The problematic sentences are 
https://github.com/UMD-AOSC/Ocean-LETKF/blob/ecf6a877ff93b324e7217dfd72f961e391c2a2f5/src/model_specific/mom6/common_mom6.f90#L129

and

https://github.com/UMD-AOSC/Ocean-LETKF/blob/ecf6a877ff93b324e7217dfd72f961e391c2a2f5/src/model_specific/mom6/common_mom6.f90#L137

`lon2d` and `lat2d` have dimension `(nlon,nlat)`, while
`work2d` has dimension `(nlon*2+1,nlat*2+1)`

Assignment of `work2d(1:nlon2d:2,1:nlat2d:2)` creates an array of size `(nlon+1,nlat+1)`, which is greater than the size of `(nlon,nlat)`, so `lon2d` and `lat2d` cannot be the receiver.

##### How to correct this bug?
`lon2d` and `lat2d` are also used in `common_obs_mom6.f90.kdtree` with the size of `(nlon,nlat)`
https://github.com/UMD-AOSC/Ocean-LETKF/blob/ecf6a877ff93b324e7217dfd72f961e391c2a2f5/src/model_specific/mom6/common_obs_mom6.f90.kdtree#L109-L110
So we should not change size of `lon2d` and `lat2d`, and we should correct RHS of assignment statement: `work2d(1:nlon2d:2,1:nlat2d:2)`.

`work2d` reads vars `x` and `y` from the file `ocean_hgrid.nc` and have dimension `(2*nlon+1,2*nlat+1)`, and MOM6 doc indicate this is because of the usage of supergrid (https://mom6.readthedocs.io/en/main/api/generated/pages/Discrete_Grids.html)

@StevePny Should we use
```
lat2d or lon2d = work2d(1:nlon2d-1:2,1:nlat2d-1:2)
```
or
```
lat2d or lon2d = work2d(2:nlon2d:2,2:nlat2d:2)
``` 
?

Thanks!

**Comment by sanAkel** [comment]
> @StevePny @sanAkel 
> 
> With a test case, I found the following 3 problems:
> 
> 
> 
> #### 1. Unallocated vars 
> 
> `ifdef DYNAMIC`, allocation for the following vars are missing:
> 
> ```
> 
>   ALLOCATE(fcori2d(nlon,nlat))
> 
>   ALLOCATE(area_t(nlon,nlat))
> 
>   ALLOCATE(height(nlon,nlat,nlev))
> 
>   ALLOCATE(wet(nlon,nlat))
> 
>   ALLOCATE(depth(nlon,nlat))
> 
> ```
> 
> #### 2. incorrect loop index 
> 
> https://github.com/UMD-AOSC/Ocean-LETKF/blob/ecf6a877ff93b324e7217dfd72f961e391c2a2f5/src/model_specific/mom6/common_mom6.f90#L156
> 
> 
> 
> Here we should use `lat(j-1)` and `lat(j+1)`, (loop over index **j** instead of **i** since `j` is for `lat` while `i` is for `lon`)
> 
> ```
> 
> d2 = cos(lat(i-1)) * cos(lat(i+1)) * (sin(dlon/2.0))**2
> 
> ```
> 
> 
> 
> #### 3. incorrect assignment (needs help)
> 
> The problematic sentences are 
> 
> https://github.com/UMD-AOSC/Ocean-LETKF/blob/ecf6a877ff93b324e7217dfd72f961e391c2a2f5/src/model_specific/mom6/common_mom6.f90#L129
> 
> 
> 
> and
> 
> 
> 
> https://github.com/UMD-AOSC/Ocean-LETKF/blob/ecf6a877ff93b324e7217dfd72f961e391c2a2f5/src/model_specific/mom6/common_mom6.f90#L137
> 
> 
> 
> `lon2d` and `lat2d` have dimension `(nlon,nlat)`, while
> 
> `work2d` has dimension `(nlon*2+1,nlat*2+1)`
> 
> 
> 
> Assignment of `work2d(1:nlon2d:2,1:nlat2d:2)` creates an array of size `(nlon+1,nlat+1)`, which is greater than the size of `(nlon,nlat)`, so `lon2d` and `lat2d` cannot be the receiver.
> 
> 
> 
> ##### How to correct this bug?
> 
> `lon2d` and `lat2d` are also used in `common_obs_mom6.f90.kdtree` with the size of `(nlon,nlat)`
> 
> https://github.com/UMD-AOSC/Ocean-LETKF/blob/ecf6a877ff93b324e7217dfd72f961e391c2a2f5/src/model_specific/mom6/common_obs_mom6.f90.kdtree#L109-L110
> 
> So we should not change size of `lon2d` and `lat2d`, and we should correct RHS of assignment statement: `work2d(1:nlon2d:2,1:nlat2d:2)`.
> 
> 
> 
> `work2d` reads vars `x` and `y` from the file `ocean_hgrid.nc` and have dimension `(2*nlon+1,2*nlat+1)`, and MOM6 doc indicates this is because of the usage of supergrid (https://mom6.readthedocs.io/en/main/api/generated/pages/Discrete_Grids.html)
> 
> 
> 
> @StevePny Should we use
> 
> ```
> 
> lat2d or lon2d = work2d(1:nlon2d-1:2,1:nlat2d-1:2)
> 
> ```
> 
> or
> 
> ```
> 
> lat2d or lon2d = work2d(2:nlon2d:2,2:nlat2d:2)
> 
> ``` 
> 
> ?
> 
> 
> 
> Thanks!
> 
> 

@cd10kfsu all grid info should be read from an ocean static file. That will of course include mosaic information. It's pretty straightforward to get that from the model: again as I said earlier, using diag_table.

**Comment by cd10kfsu** [comment]
Thanks for your comments Santha.
Please note the last bug I reported here is about the incorrect assignment due to incorrect dimension size. As long as you read vars `x` and `y` from whatever, you should encounter this problem. 
If you don't, it is probably because the compiler automatically reallocate the vars when it finds the incorrect dimension

**Comment by sanAkel** [comment]
> Thanks for your comments @sanAkel 
> 
> I have already found all the grid info and wil use diag_table in later test. Please note all the bugs I reported in this list are after I start to read in vars. 
> 
> The part that I need help is about the incorrect assignment due to incorrect dimension size. As long as you read vars `x` and `y` from whatever, you should encounter this problem. 
> 
> If you don't, it is probably because the compiler automatically reallocate the vars when it finds the incorrect dimension by default, but the dimension is incorrect.

Okay @cd10kfsu I need to stare at this. Let's discuss on Tuesday. TBH, I haven't looked at this closely!

**Comment by cd10kfsu** [comment]
Thanks!

**Comment by cd10kfsu** [comment]
@StevePny @sanAkel 
Tracked down to GEOS-ESM/MOM6 src codes (https://github.com/GEOS-ESM/MOM6/blob/d4d7fbedaf9b176ab7a8000c5813c7490b54144b/src/initialization/MOM_grid_initialize.F90#L218-L220) to understand how supergrid `x` and `y` are defined, and used for scalar variables such as Temp and Salt.

In the subroutine `subroutine set_grid_metrics_from_mosaic`, `geoLonT` is defined as
```
 218 do j=G%jsd,G%jed ; do i=G%isd,G%ied ; i2 = 2*i ; j2 = 2*j
 219    G%geoLonT(i,j) = tmpZ(i2-1,j2-1)
 220 enddo ; enddo
```
So for geoLonT (grid center for scalar variables), the mapping is
```
 geoLonT(i,j) = tmpZ(2*i-1,2*j-1)  ! tmpZ is 'y'
```

So for our MOM6-LETKF, we probably **should have**
```
lon2d = work2d(1:nlon2d-1:2,1:nlat2d-1:2)
```
to replace
https://github.com/UMD-AOSC/Ocean-LETKF/blob/ecf6a877ff93b324e7217dfd72f961e391c2a2f5/src/model_specific/mom6/common_mom6.f90#L129

Needs your final confirmation. Thanks!

**Comment by StevePny** [comment]
@cd10kfsu I recall this particular line of code, though it was many years ago. At the time, I was just trying to make sure we could read in the data from the file, but I was not 100% certain this was correct (hence the comment: "!STEVE: (ISSUE) ask GFDL for clarification"). If you have looked into the supergrid in more detail and believe your modification is correct, then that sounds good to me.

**Comment by cd10kfsu** [comment]
Thank you very much for the guidance @StevePny ! 
It seems that using the diag_table, as suggested by @sanAkel, can directly output the geoLatT. I will make one more check for it.
Will keep you updated.

**Comment by sanAkel** [comment]
- > Thank you very much for the guidance @StevePny ! 
> 
> It seems that using the diag_table, as suggested by @sanAkel, can directly output the geoLatT. I will make one more check for it.
> 
> Will keep you updated.
> 
> 
> 
> 

@cd10kfsu, there is even a simpler alternative!

Alistair (on purpose not using his GitHub id - to avoid bothering him!) has a notebook in mom6-examples which describes all there is to it reg the mosaic (I guess that's what you are calling "super grid"?). That piece of info is there even before you run the model! Look into "ocean_hgrid.nc". I need to walk you through MOM_input (a file) on Tuesday.

**Comment by cd10kfsu** [comment]
>Look into "ocean_hgrid.nc". 
@sanAkel Yes! Actually I read supergrids (MOM6 official documentation gave this name, I don't know why) `x` and `y` from `scratch/INPUT/ocean_hgrid.nc`. I'm now trying to see if they are the same as the direct output by diag_table

**Comment by sanAkel** [comment]
> >Look into "ocean_hgrid.nc". 
> 
> 
> 
> @sanAkel Yes! Actually I read supergrids (MOM6 official documentation gave this name, I don't know why) `x` and `y` from `scratch/INPUT/ocean_hgrid.nc`. I'm now trying to see if they are the same as the direct output by diag_table

You doing well! :)

Okay another hint!

In the "scratch/" look for a file "available_diagnostics*" it has some zeros in file name- so look with "wild card" if what you need is not being written out by diag-_table, see if it's there in that available diagnostics and simply add it.

**Comment by cd10kfsu** [comment]
@StevePny @sanAkel 
After comparison, it seems the correct statement should be 
```
lat2d or lon2d = work2d(2:nlon2d:2,2:nlat2d:2)
```

This is found by comparing `geolat/geolon` directly output from diag_table, and those calculated from `x` and `y`

```
% matlab codes 
clear;

% supergrids
x = ncread('ocean_hgrid.nc','x');
y = ncread('ocean_hgrid.nc','y');

% lat/lon of T points
geoLon = ncread('ocean_static.nc','geolon'); % geolon: Latitude of tracer (T) points
geoLat = ncread('ocean_static.nc','geolat'); % geolat: Longitude of tracer (T) points

% generate lat/lon of T points from supergrids x, y
[nx, ny] = size(x);
geoLon_from_x = x(2:2:nx,2:2:ny);
geoLat_from_y = y(2:2:nx,2:2:ny);

% check difference
max(geoLon(:)-geoLon_from_x(:)) % gives 0 difference
max(geoLat(:)-geoLat_from_y(:)) % gives 0 difference

```

Asked for a pull request #131 to fix this bug in addition to two other bugs mentioned above.
