### ISSUE TITLE
convert ksh to python

### ISSUE THREAD

**Issue by StevePny** [UMD-AOSC/Ocean-LETKF#23]
Convert all shell scripts (*.ksh, *.sh, *.csh) to python plus Rocoto workflow manager. This follows the HWRF approach, and seems to be the general direction things are going in the community. Among other things, this should allow for faster, more versatile plotting of output  data, as well as communication tools to broadcast and monitor results in realtime.

**Comment by cd10kfsu** [comment]
cylc+python done at https://github.com/gmao-cda/cycle-oletkf
