### ISSUE TITLE
add condition for DO_SLA=.true. here and subsequent line

### ISSUE THREAD

**Issue by StevePny** [UMD-AOSC/Ocean-LETKF#99]
https://github.com/UMD-AOSC/Ocean-LETKF/blob/a0217bd77b21a0aa829ec0c027238f2666548e9f/src/model_specific/mom6/common_mom6.f90#L555

**Comment by cd10kfsu** [comment]
This issue is resolved in the current version
https://github.com/UMD-AOSC/Ocean-LETKF/blob/c0ac0187f1ff22719484235b043980483e39b09f/src/model_specific/mom6/common_mom6.f90#L579
